from .hodge_calculator import HodgeCalculator
from src.utils.sage_imports import (
    Matrix_integer_dense,
    MPolynomialIdeal,
    MPolynomial_element,
    prod,
    Matrix,
    block_matrix,
)
from src.utils.auxiliary import get_all_sums_equal_to_d


class ArtinianGoresteinCalculator:
    def __init__(self, calculator: HodgeCalculator):
        self.calculator = calculator

    def _get_monomials_of_degree(self, deg: int) -> list[MPolynomial_element]:
        X = self.calculator.variety
        ws, xs = X.weights, X.polynomial_variables
        exps = get_all_sums_equal_to_d(list(ws), deg)
        return [prod(xi**ei for xi, ei in zip(xs, exp)) for exp in exps]

    def get_artinian_gorestein_ideal_of(
        self, x: list[int] | Matrix_integer_dense
    ) -> MPolynomialIdeal:
        """
        Computes the Artinian Gorestein ideal assocated to the primitive hodge
        cycle x. Here, x is seen as a coordinate vector in the Z-basis of the
        free Z-module of primitive hodge cycles returned by the function
        'get_basis_of_primitive_hodge_cycles'. It is a integer list of
        size r, where r is the rank of said Z-module.
        """
        X = self.calculator.variety
        R, J_f = X.polynomial_ring, X.jacobian_of_defining_polynomial
        cycle_polynomial = self.calculator.get_cycle_polynomial(x)
        cycle_polynomial_ideal = R.ideal(cycle_polynomial)
        R_formal = X.formal_polynomial_ring
        return R_formal.ideal_quotient(J_f, cycle_polynomial_ideal)

        """
        X, K = self.calculator.variety, self.calculator.variety.base_field
        R, xs, ws = X.polynomial_ring, X.polynomial_variables, X.weights
        cycle_polynomial = self.calculator.get_cycle_polynomial(x)
        mon_deg = lambda m: sum(m.degree(xi) * wi for xi, wi in zip(xs, ws))
        deg = lambda p: mon_deg(p.monomials()[0])
        cycle_deg, socle = deg(cycle_polynomial), 13  # TODO CHECK LATER
        is_jac_mon = lambda m: any(
            m.degree(xi) >= ei - 1 for xi, ei in zip(xs, X.exps)
        )
        gens: list[MPolynomial_element] = []
        for i in range(socle):
            non_jac_mons = [
                m
                for m in self._get_monomials_of_degree(cycle_deg + i)
                if not is_jac_mon(m)
            ]
            poly_to_vec = lambda p: Matrix(
                K,
                len(non_jac_mons),
                1,
                lambda i, _: p.monomial_coefficient(non_jac_mons[i]),
            )
            small_mons = self._get_monomials_of_degree(i)
            small_mons_mat = block_matrix(
                [[poly_to_vec(m * cycle_polynomial) for m in small_mons]]
            )
            # print("a")
            # sage_RREF(small_mons_mat, inv=X.formal_base_field.inv)
            # print(small_mons_mat.nrows(), small_mons_mat.ncols())
            # kernel = Matrix(K, small_mons_mat.right_kernel().basis()).transpose()
            # print(small_mons_mat.nrows(), small_mons_mat.ncols())
            kernel_gens = X.formal_base_field.generators_of_right_kernel(
                small_mons_mat
            )
            for j in range(kernel_gens.ncols()):
                curr_gen: MPolynomial_element = sum(
                    kernel_gens[i, j] * small_mons[i]
                    for i in range(len(small_mons))
                )  # type: ignore
                gens.append(curr_gen)
        return R.ideal(gens)
        """

        """
        jac_mat = block_matrix([[poly_to_vec(m) for m in mons if is_jac_mon(m)]])
        small_mons = self._get_monomials_of_degree(i)
        small_mons_mat = block_matrix(
            [[poly_to_vec(m * cycle_polynomial) for m in small_mons]]
        )
        full_mat = block_matrix([[small_mons_mat, jac_mat]])
        print(full_mat.nrows(), full_mat.ncols())
        kernel = Matrix(K, full_mat.right_kernel().basis()).transpose()
        if kernel.ncols() == 0:
            continue  # No elements of degree i
        for j in range(kernel.ncols()):
            curr_gen = sum(
                kernel[i, j] * small_mons[i] for i in range(len(small_mons))
            )
            gens.append(curr_gen)
        """

    '''
    def truncated_quotient_by(
        self, other: "WeightedHomogeneousIdealDissector", d: int
    ) -> MPolynomialIdeal:
        """
        Returns the d-th truncation of the ideal quotient (self : other), i.e.
        the ideal generated by the first d components (from 0 to d-1, excluding
        d itself) of the ideal quotient.
        """
        gens = sum([self._get_component_of_quotient(other, i) for i in range(d)], [])
        return self.formal_polynomial_ring.R.ideal(gens)

    def _get_component_of_quotient(
        self, other: "WeightedHomogeneousIdealDissector", d: int
    ) -> list[MPolynomial_element]:
        """
        Returns a basis of the d-th component of the
        ideal quotient (self : other).
        """
        for deg in range(1, d, 1):
            mons = self._get_monomials_of_degree(deg)
            other_new = other.get_basis_of_new_elements_of_component()
        return []
    '''
